language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy3"

cache: pip

install:
  - pip install -U setuptools pipenv
  - pipenv install --dev

script:
  - rm -rf dist && python setup.py sdist && pip install dist/*.tar.gz
  - pipenv run py.test -v
  - pipenv run pylama
