language: python

python:
  - "3.5"
  - "3.6"
  - "pypy3"

cache: pip

install:
  - pip install -U -e .
  - pip install -U setuptools pipenv
  - pipenv install --dev

script:
  - pipenv run py.test -v
  - pipenv run pylama
